"""colour changed to color

Revision ID: 02c55ea5b606
Revises: 64995d804a8b
Create Date: 2025-02-26 23:50:11.136811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c55ea5b606'
down_revision = '64995d804a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.drop_column('colour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colour', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('color')

    # ### end Alembic commands ###
