"""debug cart productvariant relationship 

Revision ID: 65ed243fe1ce
Revises: 85ceb5227029
Create Date: 2025-02-12 20:15:28.377073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ed243fe1ce'
down_revision = '85ceb5227029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_sku', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'product_variant', ['variant_sku'], ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variant_sku')

    # ### end Alembic commands ###
