"""Apply naming convention for foreign keys

Revision ID: e14ee558ae2f
Revises: 65ed243fe1ce
Create Date: 2025-02-12 20:21:48.550909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14ee558ae2f'
down_revision = '65ed243fe1ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_sku', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_cart_variant_sku', 'product_variant', ['variant_sku'], ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_variant_sku', type_='foreignkey')
        batch_op.drop_column('variant_sku')

    # ### end Alembic commands ###
